import type { NextPage } from "next";
import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  // const one = trpc.example.getOne.useQuery();
  const many = trpc.example.getAll.useQuery();
  const mutateTest = trpc.example.writeOne.useMutation();
  // const test = trpc.example.writeOne.useQuery({
  //   id: Math.floor(Math.random() * 151).toString(),
  // });

  const handleOnClick = (number: number) => {
    mutateTest.mutate({ id: number.toString() });
  };

  console.log(many.data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <button onClick={() => handleOnClick(23)}>click</button>
        {/* <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {one.data ? <p>{one.data.id}</p> : <p>Loading..</p>}
        </div> */}
        {/* <AuthShowcase /> */}
      </main>
    </>
  );
};

export default Home;
