import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Input from "../components/Input";
import { trpc } from "../utils/trpc";
import List from "../components/List";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { mutate: mutateCreate } = trpc.todo.create.useMutation({
    onSuccess: () => refetch(),
  });
  const { data: getAll, refetch } = trpc.todo.getAll.useQuery();
  const { mutate: mutateDelete } = trpc.todo.delete.useMutation({
    onSuccess: () => refetch(),
  });
  const { mutate: mutateUpdate } = trpc.todo.update.useMutation({
    onSuccess: () => refetch(),
  });

  const { data: session } = useSession();
  const [input, setInput] = useState<string>("");

  const handleCreateTodo = () => {
    if (input !== "") {
      mutateCreate({ text: input });
      setInput("");
    }
  };

  const handleCheckTodo = (id: string, checked: boolean) => {
    mutateUpdate({
      id,
      active: !checked,
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App TODO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          <Input
            value={input}
            handleOnChange={(e) => setInput(e.target.value)}
            handleOnClick={handleCreateTodo}
          />
          <List
            handleDeletion={(id: string) => mutateDelete({ id })}
            handleCheckbox={handleCheckTodo}
            todos={getAll}
          />
        </>
      ) : (
        <div>Please log in to see your todos</div>
      )}
    </>
  );
};

export default Home;
